const INSERT_MOVIES_PAGE = "INSERT_MOVIES_PAGE";
const INSERT_MOVIE_DETAILS = "INSERT_MOVIE_DETAILS";

const INSERT_GENRES = "INSERT_GENRES";

const ADD_SELECTED_GENRE = "ADD_SELECTED_GENRE";
const DELETE_SELECTED_GENRE = "DELETE_SELECTED_GENRE";
const CLEAR_SELECTED_GENRES = "CLEAR_SELECTED_GENRES";

const SET_GENRES_URL = "SET_GENRES_URL";
const SET_CURRENT_THEME = "SET_CURRENT_THEME";


export {
    INSERT_MOVIES_PAGE,
    INSERT_MOVIE_DETAILS,

    INSERT_GENRES,

    ADD_SELECTED_GENRE,
    DELETE_SELECTED_GENRE,
    CLEAR_SELECTED_GENRES,

    SET_GENRES_URL,
    SET_CURRENT_THEME
};